# This file was generated by GoReleaser. DO NOT EDIT.
cask "env-lease" do
  service do
    run [opt_bin/"env-lease", "daemon", "run"]
    keep_alive true
  end

  name "env-lease"
  desc "A CLI for managing temporary, leased secrets in environment files."
  homepage "https://github.com/mblarsen/env-lease"
  version "0.1.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "env-lease"

  on_macos do
    on_intel do
      url "https://github.com/mblarsen/env-lease/releases/download/v#{version}/env-lease_darwin_amd64.tar.gz"
      sha256 "95044c96577c873a51637f7a411e17fff082093f5a85c795e59452f4c9836a5a"
    end
    on_arm do
      url "https://github.com/mblarsen/env-lease/releases/download/v#{version}/env-lease_darwin_arm64.tar.gz"
      sha256 "75a3118eb7a9da036f9f856642fe40b3c92a120f09248f219e906ae9154cc41e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mblarsen/env-lease/releases/download/v#{version}/env-lease_linux_amd64.tar.gz"
      sha256 "a288a4a164c86c594047dda9372fac0fc20c0d723669035b2c8e6120ebaf0556"
    end
    on_arm do
      url "https://github.com/mblarsen/env-lease/releases/download/v#{version}/env-lease_linux_arm64.tar.gz"
      sha256 "29fee96d2c7f9c527a9cb55bdd4c44d23a54ae4a652b2029ca00e7585e1e9c1b"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/env-lease"]
    end
  end

  # No zap stanza required
end
