# This file was generated by GoReleaser. DO NOT EDIT.
cask "env-lease" do
  service do
    run [opt_bin/"env-lease", "daemon", "run"]
    keep_alive true
  end

  name "env-lease"
  desc "A CLI for managing temporary, leased secrets in environment files."
  homepage "https://github.com/mblarsen/env-lease"
  version "0.1.25"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "env-lease"

  on_macos do
    on_intel do
      url "https://github.com/mblarsen/env-lease/releases/download/v#{version}/env-lease_darwin_amd64.tar.gz"
      sha256 "4f5947ba476a4b492cdb9f31bd3ae73ae665d6de253e07b3fb525c7a0a1754c0"
    end
    on_arm do
      url "https://github.com/mblarsen/env-lease/releases/download/v#{version}/env-lease_darwin_arm64.tar.gz"
      sha256 "4109325a3661be417c158388915cb4c1cf67f6dc162cd2a29d3de16be6ae13e2"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mblarsen/env-lease/releases/download/v#{version}/env-lease_linux_amd64.tar.gz"
      sha256 "0c14abfcb7e4dfe430f16ce2bcd94c9856b2cda5020fa244e117ed460927e6e9"
    end
    on_arm do
      url "https://github.com/mblarsen/env-lease/releases/download/v#{version}/env-lease_linux_arm64.tar.gz"
      sha256 "4034e4e1e9962f3861fe2f20e84ee24263a75e0ff05dd56f0f30a8ed5bfe4dbf"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/env-lease"]
    end
    system_command "#{staged_path}/env-lease", args: ["daemon", "reload"]
  end

  # No zap stanza required
end
