# This file was generated by GoReleaser. DO NOT EDIT.
cask "env-lease" do
  service do
    run [opt_bin/"env-lease", "daemon", "run"]
    keep_alive true
  end

  name "env-lease"
  desc "A CLI for managing temporary, leased secrets in environment files."
  homepage "https://github.com/mblarsen/env-lease"
  version "0.1.23"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "env-lease"

  on_macos do
    on_intel do
      url "https://github.com/mblarsen/env-lease/releases/download/v#{version}/env-lease_darwin_amd64.tar.gz"
      sha256 "fc1f47cfc117e579326744f7d39fd6732dee3c1a91d35633930c695959095078"
    end
    on_arm do
      url "https://github.com/mblarsen/env-lease/releases/download/v#{version}/env-lease_darwin_arm64.tar.gz"
      sha256 "63186297a5afafadacefc50d34ca6fa07689be998042948e13ce169305c35d3c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mblarsen/env-lease/releases/download/v#{version}/env-lease_linux_amd64.tar.gz"
      sha256 "6bb8c3ccd50dd60507ff5384182c019d4d7be547f5da6ed6a784e949740a06ac"
    end
    on_arm do
      url "https://github.com/mblarsen/env-lease/releases/download/v#{version}/env-lease_linux_arm64.tar.gz"
      sha256 "e43cdf0fd6e6e41cff36e3fb38fe8df21fe4f9554f4a29f60215c8048f8d55e3"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/env-lease"]
    end
    system_command "#{staged_path}/env-lease", args: ["daemon", "reload"]
  end

  # No zap stanza required
end
